name: CI

on:
  push:
    branches:
      - '**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.10.0
          cache: 'npm'

      - name: Install
        run: make install

      - name: Stub Windows adapter
        run: (cd src/electron/dofus-windows-adapters; cp debug.js active.js)

      - name: Lint
        run: make lint

      - name: Forge packaging
        run: make package
