name: PUBLISH

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        type: 'choice'
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18.10.0

      - name: Install
        run: make install

      - name: Setup Windows adapter
        run: make setup-windows

      - name: Tag and publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "pboutin.dofusteam@gmail.com"
          git config --global user.name "Hel Munster"
          npm version ${{ github.event.inputs.version_type }}
          npx electron-forge publish
          git push --follow-tags
