name: PUBLISH

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.10.0
          cache: 'npm'

      - uses: actions/setup-git@v1
        with:
          token: ${{ github.token }}

      - name: Install
        run: make install

      - name: Setup Windows adapter
        run: make setup-windows

      - name: Bump patch version
        if: github.event.inputs.version_type == 'patch'
        run: npm version patch

      - name: Bump minor version
        if: github.event.inputs.version_type == 'minor'
        run: npm version minor

      - name: Git push
        run: git push --follow-tags

      - name: Forge publish
        run: npx electron-forge publish
